version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mcp
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/mcp
      DATABASE_SSL: "false"
      MCP_TOKEN: ${MCP_TOKEN:-devtoken}
      PORT: "10000"
    ports:
      - "10000:10000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
