name: Integration

on:
  push:
  pull_request:

jobs:
  add-recall:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mcp
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres" 
          --health-interval=5s 
          --health-timeout=5s 
          --health-retries=10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Start server in background
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/mcp
          DATABASE_SSL: 'false'
          MCP_TOKEN: devtoken
          PORT: '10000'
        run: |
          nohup node mcp-memory-bridge.js > server.log 2>&1 & echo $! > server.pid
          echo "PID $(cat server.pid)"

      - name: Wait for server
        run: |
          for i in {1..30}; do
            curl -s http://localhost:10000/ping && exit 0 || true;
            sleep 2;
          done
          echo "Server did not become ready"; cat server.log; exit 1

      - name: Add memory
        run: |
          curl -s -X POST http://localhost:10000/memories \
            -H 'Content-Type: application/json' \
            -H 'x-mcp-token: devtoken' \
            -d '{"text":"Integration test memory about Adam","type":"event","tags":["ci","test"]}' | tee add.json

      - name: Recall memory
        run: |
          curl -s "http://localhost:10000/memories/recall?q=Adam&token=devtoken" | tee recall.json
          grep -q '"ok":true' recall.json || (echo "Recall failed" && cat server.log && exit 1)

      - name: Show server log on success
        if: always()
        run: |
          echo "--- server.log ---"; tail -n 200 server.log || true
